// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FavoriteButtonController from "./favorite_button_controller"
application.register("favorite-button", FavoriteButtonController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SpotifyController from "./spotify_controller"
application.register("spotify", SpotifyController)
